### ISSUE TITLE
Include markdown files from sub directory does not work

### ISSUE THREAD

**Issue by HoracePGreeley** [marcel-hofer/markdown-document#20]
Unfortunately, it seems not possible to include markdown documents from sub directories:

*Code::*
``` markdown
@(include .\parts\task-1.md)
```

*Result:*
![image](https://user-images.githubusercontent.com/11772186/32278370-c9392948-bf15-11e7-9a38-309039018eec.png)

**Comment by marcel-hofer** [comment]
The regex used to parse this syntax does not support non-word characters. Therefore you can't use `-` like in the example above.

For now you can rename the file to `task1.md` and include it using:
```markdown
@(include parts/task1.md)
```

This should be fixed to allow all valid filename characters.
