### ISSUE TITLE
Won't install with Node version above 8.14

### ISSUE THREAD

**Issue by bsjausc** [marcel-hofer/markdown-document#26]
Hi! :)

We're using markdown-document and are fairly happy with it. But since we're now using a Node Version above 8.14 npm/yarn won't let us install your package anymore. We'd be glad if you could provide us a fix. 

- Thank you a lot in advance.

Kind regards from the HoracePGreeley Fanclub
C.

**Comment by marcel-hofer** [comment]
This may have been a problem with the `wkhtmltopdf` library and how its installation worked.
I updated this library to the latest version and published `v0.2.1` of the package.

I was able to sucessfully test the installation of the new package and the generation of a simple test document under node `v12.2.0` and npm `v6.9.0`.

This version also includes a fix for #20, which was reported by our friend HoracePGreeley a long time ago.
