### ISSUE TITLE
Support for latest versions of used components 

### ISSUE THREAD

**Issue by christthomc** [marcel-hofer/markdown-document#32]
As we've seen the solution isn't compatible with the latest versions of node.js.
Would you consider to upgrade the complete solution to current versions of all used components,
including TypeScript and GULP ?
We've already updated some parts excluding tests. I'f you are interested in our changes, please let me know.

Best Regards
Christian

**Comment by marcel-hofer** [comment]
I updated `gulp` and all other gulp tasks to the latest version. They should now work with the latest node LTS version (I tested it with `v12.12.0`) including the tests.

I did not update the TypeScript compiler itself to the latest version as requested - it currently works with the latest node version and the latest typescript features are not needed at the moment. I will consider an update if I want to make a larger change and need the newer TypeScript features.
